### ISSUE TITLE
doesn't start for me on OSX...

### ISSUE THREAD

**Issue by geekpete** [lukasolson/co-op-tetris#1]
$ npm start

> Co-Op-Tetris@0.0.1 start /Users/peter/Code/co-op-tetris/server
> node app

/Users/peter/Code/co-op-tetris/server/app.js:7
io.enable("browser client minification");
   ^

TypeError: io.enable is not a function
    at Object.<anonymous> (/Users/peter/Code/co-op-tetris/server/app.js:7:4)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! Co-Op-Tetris@0.0.1 start: `node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Co-Op-Tetris@0.0.1 start script 'node app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Co-Op-Tetris package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Co-Op-Tetris
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Co-Op-Tetris
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/peter/Code/co-op-tetris/server/npm-debug.log

cat  /Users/peter/Code/co-op-tetris/server/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.6.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start' ]
2 info using npm@3.10.7
3 info using node@v6.6.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle Co-Op-Tetris@0.0.1~prestart: Co-Op-Tetris@0.0.1
6 silly lifecycle Co-Op-Tetris@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle Co-Op-Tetris@0.0.1~start: Co-Op-Tetris@0.0.1
8 verbose lifecycle Co-Op-Tetris@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle Co-Op-Tetris@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/peter/Code/co-op-tetris/server/node_modules/.bin:/usr/local/Cellar/node/6.6.0/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
10 verbose lifecycle Co-Op-Tetris@0.0.1~start: CWD: /Users/peter/Code/co-op-tetris/server
11 silly lifecycle Co-Op-Tetris@0.0.1~start: Args: [ '-c', 'node app' ]
12 silly lifecycle Co-Op-Tetris@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle Co-Op-Tetris@0.0.1~start: Failed to exec start script
14 verbose stack Error: Co-Op-Tetris@0.0.1 start: `node app`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Co-Op-Tetris@0.0.1
16 verbose cwd /Users/peter/Code/co-op-tetris/server
17 error Darwin 15.6.0
18 error argv "/usr/local/Cellar/node/6.6.0/bin/node" "/usr/local/bin/npm" "start"
19 error node v6.6.0
20 error npm  v3.10.7
21 error code ELIFECYCLE
22 error Co-Op-Tetris@0.0.1 start: `node app`
22 error Exit status 1
23 error Failed at the Co-Op-Tetris@0.0.1 start script 'node app'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Co-Op-Tetris package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node app
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Co-Op-Tetris
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Co-Op-Tetris
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by lukasolson** [comment]
Fixed by 134c503a30213db60b8cfed0b2aa3b766ed25c6b.
